### PR TITLE
Quarantine records missing EndTime and set @received

### PR DESCRIPTION
**Pull request by retzkek**

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
LGTM

**Comment by retzkek** [comment]
As discussed in #gracc, I'm changing this to try to calculate an `EndTime`.

**Comment by djw8605** [comment]
Yup, are you going to just add to this pull request?

**Comment by retzkek** [comment]
Yeah, since ultimately it will still quarantine them if it can't calculate EndTime.

**Comment by retzkek** [comment]
Test results appear correct. nowall test case wasn't quarantined since collector adds `WallDuration`.
image

Not sure about changing `StartTime` though, since duplicates could end up with different `StartTime`s and have different checksums.

**Comment by retzkek** [comment]
Solution: move field calculations after the checksum. Verified that records are replaced when sending duplicates.

**Comment by djw8605** [comment]
Looks great. Do you have the reprocessing script ready?

-Derek

**Comment by retzkek** [comment]
Yep. Added the option to filter by query and some other cleanup and adding it to [gracc-tools](https://github.com/opensciencegrid/gracc-tools/pull/1) repo.

**Comment by bbockelm** [comment]
LGTM.  @retzkek @djw8605 - are we ready to merge?

**Comment by retzkek** [comment]
I'll tag this version 3.3.

**Pull request merged**
